"""Paths, icons, and tuning constants for the main window."""

from __future__ import annotations

from blab.paths import APP_ROOT

DEFAULT_MESH_SCALE_FACTOR = 0.001

LIVE_PLOT_REFRESH_INTERVAL_MS = 250

ATH_BUNDLE_DIR = APP_ROOT / "ath"

GENERATED_GEOMETRY_ROOT = APP_ROOT / "runs" / "generated_geometry"

GMSH_BUNDLE_EXE = APP_ROOT / "gmsh" / "gmsh-4.15.2-Windows64" / "gmsh.exe"

HELP_GUIDE_PDF = APP_ROOT / "docs" / "Boundary Lab Guide.pdf"

SAVE_DARK_ICON = APP_ROOT / "assets" / "save_dark.ico"

SAVE_LIGHT_ICON = APP_ROOT / "assets" / "save_light.ico"

CAPTURE_CONTOURS_DARK_ICON = APP_ROOT / "assets" / "capturecontours_dark.ico"

CAPTURE_CONTOURS_LIGHT_ICON = APP_ROOT / "assets" / "capturecontours_light.ico"

CLEAR_CONTOURS_DARK_ICON = APP_ROOT / "assets" / "clearcontours_dark.ico"

CLEAR_CONTOURS_LIGHT_ICON = APP_ROOT / "assets" / "clearcontours_light.ico"

FEM_PREVIEW_DARK_ICON = APP_ROOT / "assets" / "FEMTetra_dark.ico"

FEM_PREVIEW_LIGHT_ICON = APP_ROOT / "assets" / "FEMTetra_light.ico"

BEM_PREVIEW_DARK_ICON = APP_ROOT / "assets" / "BEMTri_dark.ico"

BEM_PREVIEW_LIGHT_ICON = APP_ROOT / "assets" / "BEMTri_light.ico"

ADD_DESIGN_TAB_LABEL = "+"

DEFAULT_DOCK_STATE_B64 = (
    "AAAA/wAAAAD9AAAAAQAAAAAAAAduAAADdvwCAAAAAfwAAAAAAAADdgAAAG4A/////AEAAAAG+wAAAB4AYQB0AGgAXwBl"
    "AGQAaQB0AG8AcgBfAGQAbwBjAGsBAAAAAAAAAdsAAACFAP////wAAAHfAAADRQAAAGoA/////AIAAAAC+wAAACIAbQBl"
    "AHMAaABfAHAAcgBlAHYAaQBlAHcAXwBkAG8AYwBrAQAAAAAAAAN2AAAANAD////7AAAAHABzAHAAaQBuAG8AcgBhAG0A"
    "YQBfAGQAbwBjAGsIAAAB4AAAAZYAAAAiAP////sAAAAUAHAAbABvAHQAcwBfAGQAbwBjAGsBAAAE9QAAAnkAAAAAAAAA"
    "APwAAAUoAAACRgAAAHsA/////AIAAAAC+wAAACwAaABvAHIAaQB6AG8AbgB0AGEAbABfAGkAcwBvAGIAYQByAF8AZABv"
    "AGMAawEAAAAAAAABugAAACIA////+wAAACgAdgBlAHIAdABpAGMAYQBsAF8AaQBzAG8AYgBhAHIAXwBkAG8AYwBrAQAA"
    "Ab4AAAG4AAAAIgD////7AAAALgBhAGMAbwB1AHMAdABpAGMAXwBpAG0AcABlAGQAYQBuAGMAZQBfAGQAbwBjAGsAAAAA"
    "AP////8AAACNAP////sAAAA+AG8AbgBfAGEAeABpAHMAXwBmAHIAZQBxAHUAZQBuAGMAeQBfAHIAZQBzAHAAbwBuAHMA"
    "ZQBfAGQAbwBjAGsIAAAF/AAAAXIAAAC6AP///wAAAAAAAAN2AAAABAAAAAQAAAAIAAAACPwAAAAA"
)
